// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (plan, billing_note)
VALUES ($1, $2)
RETURNING id, plan, status, billing_note, created_at
`

type CreateAccountParams struct {
	Plan        string
	BillingNote *string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Plan, arg.BillingNote)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Plan,
		&i.Status,
		&i.BillingNote,
		&i.CreatedAt,
	)
	return i, err
}

const createFamilyMember = `-- name: CreateFamilyMember :one
INSERT INTO family_members (account_id, name, phone_e164, relation, language, priority, whatsapp_opt_in_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, name, phone_e164, relation, language, priority, whatsapp_opt_in_at, created_at
`

type CreateFamilyMemberParams struct {
	AccountID       uuid.UUID
	Name            string
	PhoneE164       string
	Relation        *string
	Language        string
	Priority        int32
	WhatsappOptInAt *time.Time
}

func (q *Queries) CreateFamilyMember(ctx context.Context, arg CreateFamilyMemberParams) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, createFamilyMember,
		arg.AccountID,
		arg.Name,
		arg.PhoneE164,
		arg.Relation,
		arg.Language,
		arg.Priority,
		arg.WhatsappOptInAt,
	)
	var i FamilyMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.PhoneE164,
		&i.Relation,
		&i.Language,
		&i.Priority,
		&i.WhatsappOptInAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, plan, status, billing_note, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Plan,
		&i.Status,
		&i.BillingNote,
		&i.CreatedAt,
	)
	return i, err
}

const listFamilyMembers = `-- name: ListFamilyMembers :many
SELECT id, account_id, name, phone_e164, relation, language, priority, whatsapp_opt_in_at, created_at FROM family_members WHERE account_id = $1 ORDER BY priority
`

func (q *Queries) ListFamilyMembers(ctx context.Context, accountID uuid.UUID) ([]FamilyMember, error) {
	rows, err := q.db.Query(ctx, listFamilyMembers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamilyMember
	for rows.Next() {
		var i FamilyMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.PhoneE164,
			&i.Relation,
			&i.Language,
			&i.Priority,
			&i.WhatsappOptInAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
