// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const averageCallSeconds = `-- name: AverageCallSeconds :one
SELECT COALESCE(avg(duration_sec), 0)::float8 FROM calls
WHERE status = 'completed' AND duration_sec IS NOT NULL AND ended_at >= $1
`

func (q *Queries) AverageCallSeconds(ctx context.Context, since *time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, averageCallSeconds, since)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const costPerAccount = `-- name: CostPerAccount :many
SELECT a.id, a.plan, COALESCE(sum(c.cost_paise), 0)::bigint AS paise,
       (SELECT string_agg(p2.preferred_name, ', ') FROM parents p2 WHERE p2.account_id = a.id) AS parents
FROM accounts a JOIN parents p ON p.account_id = a.id JOIN calls c ON c.parent_id = p.id
WHERE c.scheduled_for >= $1
GROUP BY a.id, a.plan
ORDER BY paise DESC
`

type CostPerAccountRow struct {
	ID      uuid.UUID
	Plan    string
	Paise   int64
	Parents []byte
}

func (q *Queries) CostPerAccount(ctx context.Context, since time.Time) ([]CostPerAccountRow, error) {
	rows, err := q.db.Query(ctx, costPerAccount, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostPerAccountRow
	for rows.Next() {
		var i CostPerAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Plan,
			&i.Paise,
			&i.Parents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAttemptsForSlot = `-- name: CountAttemptsForSlot :one
SELECT count(*)::int FROM calls WHERE slot_id = $1
`

func (q *Queries) CountAttemptsForSlot(ctx context.Context, slotID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAttemptsForSlot, slotID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const eraseAlertDetails = `-- name: EraseAlertDetails :exec
UPDATE alerts SET detail_enc = NULL, review_note_enc = NULL WHERE parent_id = $1
`

func (q *Queries) EraseAlertDetails(ctx context.Context, parentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseAlertDetails, parentID)
	return err
}

const eraseMedicines = `-- name: EraseMedicines :exec
DELETE FROM medicines WHERE parent_id = $1
`

func (q *Queries) EraseMedicines(ctx context.Context, parentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseMedicines, parentID)
	return err
}

const eraseMemories = `-- name: EraseMemories :exec
DELETE FROM memories WHERE parent_id = $1
`

func (q *Queries) EraseMemories(ctx context.Context, parentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseMemories, parentID)
	return err
}

const eraseParent = `-- name: EraseParent :exec
UPDATE parents
SET preferred_name = 'Erased', phone_e164 = $1, interests_enc = NULL, safe_word_enc = NULL,
    local_contact_name = NULL, local_contact_phone_e164 = NULL, status = 'stopped'
WHERE id = $2
`

type EraseParentParams struct {
	PlaceholderPhone string
	ID               uuid.UUID
}

// Anonymise on request (SPEC §13). The phone becomes a non-dialable
// placeholder that still satisfies the E.164 and uniqueness checks.
func (q *Queries) EraseParent(ctx context.Context, arg EraseParentParams) error {
	_, err := q.db.Exec(ctx, eraseParent, arg.PlaceholderPhone, arg.ID)
	return err
}

const eraseReports = `-- name: EraseReports :exec
DELETE FROM call_reports r USING calls c WHERE r.call_id = c.id AND c.parent_id = $1
`

func (q *Queries) EraseReports(ctx context.Context, parentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseReports, parentID)
	return err
}

const eraseTranscripts = `-- name: EraseTranscripts :exec
DELETE FROM transcripts t USING calls c WHERE t.call_id = c.id AND c.parent_id = $1
`

func (q *Queries) EraseTranscripts(ctx context.Context, parentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseTranscripts, parentID)
	return err
}

const listAllCallsForParent = `-- name: ListAllCallsForParent :many
SELECT id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason FROM calls WHERE parent_id = $1 ORDER BY scheduled_for
`

func (q *Queries) ListAllCallsForParent(ctx context.Context, parentID uuid.UUID) ([]Call, error) {
	rows, err := q.db.Query(ctx, listAllCallsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.ParentID,
			&i.AttemptNo,
			&i.ScheduledFor,
			&i.Status,
			&i.Provider,
			&i.ProviderCallID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.CostPaise,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMedicines = `-- name: ListAllMedicines :many
SELECT id, parent_id, name_enc, timing, active FROM medicines WHERE parent_id = $1 ORDER BY active DESC, timing, id
`

func (q *Queries) ListAllMedicines(ctx context.Context, parentID uuid.UUID) ([]Medicine, error) {
	rows, err := q.db.Query(ctx, listAllMedicines, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medicine
	for rows.Next() {
		var i Medicine
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.NameEnc,
			&i.Timing,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMemories = `-- name: ListAllMemories :many
SELECT id, parent_id, kind, content_enc, source_call_id, expires_at, created_at FROM memories WHERE parent_id = $1 ORDER BY created_at
`

func (q *Queries) ListAllMemories(ctx context.Context, parentID uuid.UUID) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listAllMemories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.ContentEnc,
			&i.SourceCallID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallsBetween = `-- name: ListCallsBetween :many
SELECT c.id, c.attempt_no, c.status, c.scheduled_for, c.duration_sec, c.end_reason,
       p.id AS parent_id, p.preferred_name
FROM calls c JOIN parents p ON p.id = c.parent_id
WHERE c.scheduled_for >= $1 AND c.scheduled_for < $2
ORDER BY c.scheduled_for, p.preferred_name
`

type ListCallsBetweenParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type ListCallsBetweenRow struct {
	ID            uuid.UUID
	AttemptNo     int32
	Status        string
	ScheduledFor  time.Time
	DurationSec   *int32
	EndReason     *string
	ParentID      uuid.UUID
	PreferredName string
}

func (q *Queries) ListCallsBetween(ctx context.Context, arg ListCallsBetweenParams) ([]ListCallsBetweenRow, error) {
	rows, err := q.db.Query(ctx, listCallsBetween, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallsBetweenRow
	for rows.Next() {
		var i ListCallsBetweenRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptNo,
			&i.Status,
			&i.ScheduledFor,
			&i.DurationSec,
			&i.EndReason,
			&i.ParentID,
			&i.PreferredName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentsForParent = `-- name: ListConsentsForParent :many
SELECT id, parent_id, kind, given_by, method, text_version, evidence_ref, given_at, withdrawn_at FROM consents WHERE parent_id = $1 ORDER BY given_at DESC, id
`

func (q *Queries) ListConsentsForParent(ctx context.Context, parentID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.Query(ctx, listConsentsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consent
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.GivenBy,
			&i.Method,
			&i.TextVersion,
			&i.EvidenceRef,
			&i.GivenAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundForAccount = `-- name: ListInboundForAccount :many
SELECT i.id, i.family_member_id, i.from_e164, i.kind, i.body_enc, i.handled_at, i.received_at FROM inbound_messages i JOIN family_members m ON m.id = i.family_member_id
WHERE m.account_id = $1 ORDER BY i.received_at
`

func (q *Queries) ListInboundForAccount(ctx context.Context, accountID uuid.UUID) ([]InboundMessage, error) {
	rows, err := q.db.Query(ctx, listInboundForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboundMessage
	for rows.Next() {
		var i InboundMessage
		if err := rows.Scan(
			&i.ID,
			&i.FamilyMemberID,
			&i.FromE164,
			&i.Kind,
			&i.BodyEnc,
			&i.HandledAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAlerts = `-- name: ListOpenAlerts :many
SELECT al.id, al.parent_id, al.call_id, al.slot_id, al.type, al.category, al.source, al.detail_enc, al.status, al.escalation_step, al.acknowledged_by, al.acknowledged_at, al.reviewed_by, al.reviewed_at, al.review_note_enc, al.created_at, p.preferred_name
FROM alerts al JOIN parents p ON p.id = al.parent_id
WHERE al.status IN ('open', 'notified')
ORDER BY CASE al.type WHEN 'emergency' THEN 0 WHEN 'urgent' THEN 1 WHEN 'scam' THEN 2 WHEN 'missed_calls' THEN 3 ELSE 4 END,
         al.created_at
LIMIT 200
`

type ListOpenAlertsRow struct {
	ID             uuid.UUID
	ParentID       uuid.UUID
	CallID         *uuid.UUID
	SlotID         *uuid.UUID
	Type           string
	Category       string
	Source         string
	DetailEnc      []byte
	Status         string
	EscalationStep int32
	AcknowledgedBy *uuid.UUID
	AcknowledgedAt *time.Time
	ReviewedBy     *string
	ReviewedAt     *time.Time
	ReviewNoteEnc  []byte
	CreatedAt      time.Time
	PreferredName  string
}

func (q *Queries) ListOpenAlerts(ctx context.Context) ([]ListOpenAlertsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenAlertsRow
	for rows.Next() {
		var i ListOpenAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CallID,
			&i.SlotID,
			&i.Type,
			&i.Category,
			&i.Source,
			&i.DetailEnc,
			&i.Status,
			&i.EscalationStep,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNoteEnc,
			&i.CreatedAt,
			&i.PreferredName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentsOverview = `-- name: ListParentsOverview :many
SELECT p.id, p.preferred_name, p.status, p.language, p.timezone, p.call_time_local, p.first_call_done_at,
       a.plan, a.status AS account_status,
       (SELECT count(DISTINCT c.kind) FROM consents c
         WHERE c.parent_id = p.id AND c.withdrawn_at IS NULL
           AND c.kind IN ('calls', 'data_processing', 'share_with_family'))::int AS required_consents,
       (SELECT count(*) FROM alerts al WHERE al.parent_id = p.id AND al.status IN ('open', 'notified'))::int AS open_alerts
FROM parents p JOIN accounts a ON a.id = p.account_id
ORDER BY p.created_at DESC
LIMIT 500
`

type ListParentsOverviewRow struct {
	ID               uuid.UUID
	PreferredName    string
	Status           string
	Language         string
	Timezone         string
	CallTimeLocal    pgtype.Time
	FirstCallDoneAt  *time.Time
	Plan             string
	AccountStatus    string
	RequiredConsents int32
	OpenAlerts       int32
}

func (q *Queries) ListParentsOverview(ctx context.Context) ([]ListParentsOverviewRow, error) {
	rows, err := q.db.Query(ctx, listParentsOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParentsOverviewRow
	for rows.Next() {
		var i ListParentsOverviewRow
		if err := rows.Scan(
			&i.ID,
			&i.PreferredName,
			&i.Status,
			&i.Language,
			&i.Timezone,
			&i.CallTimeLocal,
			&i.FirstCallDoneAt,
			&i.Plan,
			&i.AccountStatus,
			&i.RequiredConsents,
			&i.OpenAlerts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCallsForParent = `-- name: ListRecentCallsForParent :many
SELECT c.id, c.slot_id, c.parent_id, c.attempt_no, c.scheduled_for, c.status, c.provider, c.provider_call_id, c.started_at, c.ended_at, c.duration_sec, c.cost_paise, c.end_reason, r.needs_review AS report_needs_review, r.red_flag_count AS report_red_flags, r.schema_version AS report_version
FROM calls c LEFT JOIN call_reports r ON r.call_id = c.id
WHERE c.parent_id = $1
ORDER BY c.scheduled_for DESC
LIMIT $2
`

type ListRecentCallsForParentParams struct {
	ParentID uuid.UUID
	MaxItems int32
}

type ListRecentCallsForParentRow struct {
	ID                uuid.UUID
	SlotID            uuid.UUID
	ParentID          uuid.UUID
	AttemptNo         int32
	ScheduledFor      time.Time
	Status            string
	Provider          string
	ProviderCallID    *string
	StartedAt         *time.Time
	EndedAt           *time.Time
	DurationSec       *int32
	CostPaise         *int64
	EndReason         *string
	ReportNeedsReview *bool
	ReportRedFlags    *int32
	ReportVersion     *string
}

func (q *Queries) ListRecentCallsForParent(ctx context.Context, arg ListRecentCallsForParentParams) ([]ListRecentCallsForParentRow, error) {
	rows, err := q.db.Query(ctx, listRecentCallsForParent, arg.ParentID, arg.MaxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentCallsForParentRow
	for rows.Next() {
		var i ListRecentCallsForParentRow
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.ParentID,
			&i.AttemptNo,
			&i.ScheduledFor,
			&i.Status,
			&i.Provider,
			&i.ProviderCallID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.CostPaise,
			&i.EndReason,
			&i.ReportNeedsReview,
			&i.ReportRedFlags,
			&i.ReportVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsForParent = `-- name: ListReportsForParent :many
SELECT r.call_id, r.schema_version, r.report_enc, r.red_flag_count, r.confidence, r.needs_review, r.model, r.created_at, r.reviewed_by, r.reviewed_at FROM call_reports r JOIN calls c ON c.id = r.call_id WHERE c.parent_id = $1 ORDER BY r.created_at
`

func (q *Queries) ListReportsForParent(ctx context.Context, parentID uuid.UUID) ([]CallReport, error) {
	rows, err := q.db.Query(ctx, listReportsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallReport
	for rows.Next() {
		var i CallReport
		if err := rows.Scan(
			&i.CallID,
			&i.SchemaVersion,
			&i.ReportEnc,
			&i.RedFlagCount,
			&i.Confidence,
			&i.NeedsReview,
			&i.Model,
			&i.CreatedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsToReview = `-- name: ListReportsToReview :many
SELECT r.call_id, r.confidence, r.red_flag_count, r.schema_version, r.created_at, p.id AS parent_id, p.preferred_name
FROM call_reports r JOIN calls c ON c.id = r.call_id JOIN parents p ON p.id = c.parent_id
WHERE r.needs_review AND r.reviewed_at IS NULL
ORDER BY r.created_at
LIMIT 200
`

type ListReportsToReviewRow struct {
	CallID        uuid.UUID
	Confidence    float32
	RedFlagCount  int32
	SchemaVersion string
	CreatedAt     time.Time
	ParentID      uuid.UUID
	PreferredName string
}

func (q *Queries) ListReportsToReview(ctx context.Context) ([]ListReportsToReviewRow, error) {
	rows, err := q.db.Query(ctx, listReportsToReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsToReviewRow
	for rows.Next() {
		var i ListReportsToReviewRow
		if err := rows.Scan(
			&i.CallID,
			&i.Confidence,
			&i.RedFlagCount,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.ParentID,
			&i.PreferredName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptsForParent = `-- name: ListTranscriptsForParent :many
SELECT t.call_id, t.turns_enc, t.language, t.delete_after FROM transcripts t JOIN calls c ON c.id = t.call_id WHERE c.parent_id = $1 ORDER BY c.scheduled_for
`

func (q *Queries) ListTranscriptsForParent(ctx context.Context, parentID uuid.UUID) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, listTranscriptsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcript
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.CallID,
			&i.TurnsEnc,
			&i.Language,
			&i.DeleteAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnhandledInbound = `-- name: ListUnhandledInbound :many
SELECT i.id, i.family_member_id, i.from_e164, i.kind, i.body_enc, i.handled_at, i.received_at, m.name AS member_name
FROM inbound_messages i LEFT JOIN family_members m ON m.id = i.family_member_id
WHERE i.handled_at IS NULL
ORDER BY i.received_at
LIMIT 200
`

type ListUnhandledInboundRow struct {
	ID             uuid.UUID
	FamilyMemberID *uuid.UUID
	FromE164       string
	Kind           string
	BodyEnc        []byte
	HandledAt      *time.Time
	ReceivedAt     time.Time
	MemberName     *string
}

func (q *Queries) ListUnhandledInbound(ctx context.Context) ([]ListUnhandledInboundRow, error) {
	rows, err := q.db.Query(ctx, listUnhandledInbound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnhandledInboundRow
	for rows.Next() {
		var i ListUnhandledInboundRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyMemberID,
			&i.FromE164,
			&i.Kind,
			&i.BodyEnc,
			&i.HandledAt,
			&i.ReceivedAt,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboundHandled = `-- name: MarkInboundHandled :execrows
UPDATE inbound_messages SET handled_at = $1 WHERE id = $2 AND handled_at IS NULL
`

type MarkInboundHandledParams struct {
	HandledAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) MarkInboundHandled(ctx context.Context, arg MarkInboundHandledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInboundHandled, arg.HandledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReportReviewed = `-- name: MarkReportReviewed :execrows
UPDATE call_reports SET reviewed_by = $1, reviewed_at = $2
WHERE call_id = $3 AND reviewed_at IS NULL
`

type MarkReportReviewedParams struct {
	ReviewedBy *string
	ReviewedAt *time.Time
	CallID     uuid.UUID
}

func (q *Queries) MarkReportReviewed(ctx context.Context, arg MarkReportReviewedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReportReviewed, arg.ReviewedBy, arg.ReviewedAt, arg.CallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const medianSummaryMinutes = `-- name: MedianSummaryMinutes :one
SELECT COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM (n.sent_at - c.ended_at)) / 60), 0)::float8
FROM notifications n JOIN calls c ON c.id = n.call_id
WHERE n.template = 'daily_summary_v1' AND n.sent_at IS NOT NULL AND c.ended_at IS NOT NULL AND c.ended_at >= $1
`

// Minutes from the end of a call to its first daily summary going out.
func (q *Queries) MedianSummaryMinutes(ctx context.Context, since *time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, medianSummaryMinutes, since)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const openAlertsByType = `-- name: OpenAlertsByType :many
SELECT type, count(*)::int AS n FROM alerts WHERE status IN ('open', 'notified') GROUP BY type ORDER BY type
`

type OpenAlertsByTypeRow struct {
	Type string
	N    int32
}

func (q *Queries) OpenAlertsByType(ctx context.Context) ([]OpenAlertsByTypeRow, error) {
	rows, err := q.db.Query(ctx, openAlertsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenAlertsByTypeRow
	for rows.Next() {
		var i OpenAlertsByTypeRow
		if err := rows.Scan(&i.Type, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickupRates = `-- name: PickupRates :many
SELECT p.id, p.preferred_name,
       count(*) FILTER (WHERE s.status = 'completed')::int AS completed,
       count(*) FILTER (WHERE s.status <> 'cancelled')::int AS due
FROM parents p JOIN call_slots s ON s.parent_id = p.id
WHERE s.local_date >= $1
GROUP BY p.id, p.preferred_name
ORDER BY p.preferred_name
`

type PickupRatesRow struct {
	ID            uuid.UUID
	PreferredName string
	Completed     int32
	Due           int32
}

// Completed slots over due (non-cancelled) slots per parent since a date.
func (q *Queries) PickupRates(ctx context.Context, since pgtype.Date) ([]PickupRatesRow, error) {
	rows, err := q.db.Query(ctx, pickupRates, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PickupRatesRow
	for rows.Next() {
		var i PickupRatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PreferredName,
			&i.Completed,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :execrows
UPDATE alerts SET status = $1, reviewed_by = $2, reviewed_at = $3, review_note_enc = $4
WHERE id = $5 AND status IN ('open', 'notified', 'acknowledged')
`

type ResolveAlertParams struct {
	Status        string
	ReviewedBy    *string
	ReviewedAt    *time.Time
	ReviewNoteEnc []byte
	ID            uuid.UUID
}

func (q *Queries) ResolveAlert(ctx context.Context, arg ResolveAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveAlert,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNoteEnc,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMedicineActive = `-- name: SetMedicineActive :exec
UPDATE medicines SET active = $1 WHERE id = $2 AND parent_id = $3
`

type SetMedicineActiveParams struct {
	Active   bool
	ID       uuid.UUID
	ParentID uuid.UUID
}

func (q *Queries) SetMedicineActive(ctx context.Context, arg SetMedicineActiveParams) error {
	_, err := q.db.Exec(ctx, setMedicineActive, arg.Active, arg.ID, arg.ParentID)
	return err
}

const updateParentSchedule = `-- name: UpdateParentSchedule :exec
UPDATE parents SET call_time_local = $1, window_start = $2, window_end = $3
WHERE id = $4
`

type UpdateParentScheduleParams struct {
	CallTimeLocal pgtype.Time
	WindowStart   pgtype.Time
	WindowEnd     pgtype.Time
	ID            uuid.UUID
}

func (q *Queries) UpdateParentSchedule(ctx context.Context, arg UpdateParentScheduleParams) error {
	_, err := q.db.Exec(ctx, updateParentSchedule,
		arg.CallTimeLocal,
		arg.WindowStart,
		arg.WindowEnd,
		arg.ID,
	)
	return err
}
