// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAlert = `-- name: GetAlert :one
SELECT id, parent_id, call_id, slot_id, type, category, source, detail_enc, status, escalation_step, acknowledged_by, acknowledged_at, reviewed_by, reviewed_at, review_note_enc, created_at FROM alerts WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CallID,
		&i.SlotID,
		&i.Type,
		&i.Category,
		&i.Source,
		&i.DetailEnc,
		&i.Status,
		&i.EscalationStep,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNoteEnc,
		&i.CreatedAt,
	)
	return i, err
}

const insertParentAlert = `-- name: InsertParentAlert :one
INSERT INTO alerts (parent_id, type, category, source, detail_enc)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertParentAlertParams struct {
	ParentID  uuid.UUID
	Type      string
	Category  string
	Source    string
	DetailEnc []byte
}

// Alerts tied to neither a call nor a slot (for example, watch trends).
func (q *Queries) InsertParentAlert(ctx context.Context, arg InsertParentAlertParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertParentAlert,
		arg.ParentID,
		arg.Type,
		arg.Category,
		arg.Source,
		arg.DetailEnc,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSlotAlert = `-- name: InsertSlotAlert :one
INSERT INTO alerts (parent_id, slot_id, type, category, source)
VALUES ($1, $2, $3, $4, 'rule')
ON CONFLICT (slot_id, category) WHERE slot_id IS NOT NULL DO NOTHING
RETURNING id
`

type InsertSlotAlertParams struct {
	ParentID uuid.UUID
	SlotID   *uuid.UUID
	Type     string
	Category string
}

// missed_calls alerts, one per slot. Returns no row for a duplicate.
func (q *Queries) InsertSlotAlert(ctx context.Context, arg InsertSlotAlertParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSlotAlert,
		arg.ParentID,
		arg.SlotID,
		arg.Type,
		arg.Category,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAlertsForCall = `-- name: ListAlertsForCall :many
SELECT id, parent_id, call_id, slot_id, type, category, source, detail_enc, status, escalation_step, acknowledged_by, acknowledged_at, reviewed_by, reviewed_at, review_note_enc, created_at FROM alerts WHERE call_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListAlertsForCall(ctx context.Context, callID *uuid.UUID) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsForCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CallID,
			&i.SlotID,
			&i.Type,
			&i.Category,
			&i.Source,
			&i.DetailEnc,
			&i.Status,
			&i.EscalationStep,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNoteEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsForParent = `-- name: ListAlertsForParent :many
SELECT id, parent_id, call_id, slot_id, type, category, source, detail_enc, status, escalation_step, acknowledged_by, acknowledged_at, reviewed_by, reviewed_at, review_note_enc, created_at FROM alerts WHERE parent_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListAlertsForParent(ctx context.Context, parentID uuid.UUID) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CallID,
			&i.SlotID,
			&i.Type,
			&i.Category,
			&i.Source,
			&i.DetailEnc,
			&i.Status,
			&i.EscalationStep,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNoteEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCallAlert = `-- name: UpsertCallAlert :one
INSERT INTO alerts (parent_id, call_id, type, category, source, detail_enc)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (call_id, category) WHERE call_id IS NOT NULL DO UPDATE
SET type = CASE
      WHEN alerts.type = 'emergency' OR EXCLUDED.type = 'emergency' THEN 'emergency'
      WHEN alerts.type = 'urgent' OR EXCLUDED.type = 'urgent' THEN 'urgent'
      ELSE EXCLUDED.type END,
    detail_enc = COALESCE(alerts.detail_enc, EXCLUDED.detail_enc)
RETURNING id, type, (xmax = 0)::boolean AS inserted
`

type UpsertCallAlertParams struct {
	ParentID  uuid.UUID
	CallID    *uuid.UUID
	Type      string
	Category  string
	Source    string
	DetailEnc []byte
}

type UpsertCallAlertRow struct {
	ID       uuid.UUID
	Type     string
	Inserted bool
}

// One alert per (call_id, category): mid-call tool alerts and post-call
// findings merge into the same row. An emergency is never downgraded.
func (q *Queries) UpsertCallAlert(ctx context.Context, arg UpsertCallAlertParams) (UpsertCallAlertRow, error) {
	row := q.db.QueryRow(ctx, upsertCallAlert,
		arg.ParentID,
		arg.CallID,
		arg.Type,
		arg.Category,
		arg.Source,
		arg.DetailEnc,
	)
	var i UpsertCallAlertRow
	err := row.Scan(&i.ID, &i.Type, &i.Inserted)
	return i, err
}
