// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package db

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor, action, entity, entity_id, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	Actor    string
	Action   string
	Entity   string
	EntityID string
	Details  []byte
}

// details must never hold health data or full phone numbers.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Details,
	)
	return err
}
