// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calls.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelOpenCallsForParent = `-- name: CancelOpenCallsForParent :execrows
UPDATE calls SET status = 'cancelled', end_reason = $1, ended_at = $2
WHERE parent_id = $3 AND status = 'scheduled'
`

type CancelOpenCallsForParentParams struct {
	EndReason *string
	Now       *time.Time
	ParentID  uuid.UUID
}

// Stop request or consent withdrawal: nothing scheduled may still dial.
func (q *Queries) CancelOpenCallsForParent(ctx context.Context, arg CancelOpenCallsForParentParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOpenCallsForParent, arg.EndReason, arg.Now, arg.ParentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelPendingSlotsForParent = `-- name: CancelPendingSlotsForParent :execrows
UPDATE call_slots SET status = 'cancelled' WHERE parent_id = $1 AND status = 'pending'
`

func (q *Queries) CancelPendingSlotsForParent(ctx context.Context, parentID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingSlotsForParent, parentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCall = `-- name: GetCall :one
SELECT id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason FROM calls WHERE id = $1
`

func (q *Queries) GetCall(ctx context.Context, id uuid.UUID) (Call, error) {
	row := q.db.QueryRow(ctx, getCall, id)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.ParentID,
		&i.AttemptNo,
		&i.ScheduledFor,
		&i.Status,
		&i.Provider,
		&i.ProviderCallID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.CostPaise,
		&i.EndReason,
	)
	return i, err
}

const getCallByProviderID = `-- name: GetCallByProviderID :one
SELECT id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason FROM calls WHERE provider = $1 AND provider_call_id = $2
`

type GetCallByProviderIDParams struct {
	Provider       string
	ProviderCallID *string
}

func (q *Queries) GetCallByProviderID(ctx context.Context, arg GetCallByProviderIDParams) (Call, error) {
	row := q.db.QueryRow(ctx, getCallByProviderID, arg.Provider, arg.ProviderCallID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.ParentID,
		&i.AttemptNo,
		&i.ScheduledFor,
		&i.Status,
		&i.Provider,
		&i.ProviderCallID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.CostPaise,
		&i.EndReason,
	)
	return i, err
}

const getCallForUpdate = `-- name: GetCallForUpdate :one
SELECT id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason FROM calls WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCallForUpdate(ctx context.Context, id uuid.UUID) (Call, error) {
	row := q.db.QueryRow(ctx, getCallForUpdate, id)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.ParentID,
		&i.AttemptNo,
		&i.ScheduledFor,
		&i.Status,
		&i.Provider,
		&i.ProviderCallID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.CostPaise,
		&i.EndReason,
	)
	return i, err
}

const getSlot = `-- name: GetSlot :one
SELECT id, parent_id, local_date, status FROM call_slots WHERE id = $1
`

func (q *Queries) GetSlot(ctx context.Context, id uuid.UUID) (CallSlot, error) {
	row := q.db.QueryRow(ctx, getSlot, id)
	var i CallSlot
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.LocalDate,
		&i.Status,
	)
	return i, err
}

const getTranscript = `-- name: GetTranscript :one
SELECT call_id, turns_enc, language, delete_after FROM transcripts WHERE call_id = $1
`

func (q *Queries) GetTranscript(ctx context.Context, callID uuid.UUID) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscript, callID)
	var i Transcript
	err := row.Scan(
		&i.CallID,
		&i.TurnsEnc,
		&i.Language,
		&i.DeleteAfter,
	)
	return i, err
}

const insertTranscript = `-- name: InsertTranscript :execrows
INSERT INTO transcripts (call_id, turns_enc, language, delete_after)
VALUES ($1, $2, $3, $4)
ON CONFLICT (call_id) DO NOTHING
`

type InsertTranscriptParams struct {
	CallID      uuid.UUID
	TurnsEnc    []byte
	Language    *string
	DeleteAfter time.Time
}

func (q *Queries) InsertTranscript(ctx context.Context, arg InsertTranscriptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTranscript,
		arg.CallID,
		arg.TurnsEnc,
		arg.Language,
		arg.DeleteAfter,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (provider, event_id, received_at)
VALUES ($1, $2, $3)
ON CONFLICT (provider, event_id) DO NOTHING
RETURNING event_id
`

type InsertWebhookEventParams struct {
	Provider   string
	EventID    string
	ReceivedAt time.Time
}

// Returns no row for a duplicate (provider, event_id).
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.Provider, arg.EventID, arg.ReceivedAt)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const listCallsForSlot = `-- name: ListCallsForSlot :many
SELECT id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason FROM calls WHERE slot_id = $1 ORDER BY attempt_no
`

func (q *Queries) ListCallsForSlot(ctx context.Context, slotID uuid.UUID) ([]Call, error) {
	rows, err := q.db.Query(ctx, listCallsForSlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.ParentID,
			&i.AttemptNo,
			&i.ScheduledFor,
			&i.Status,
			&i.Provider,
			&i.ProviderCallID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.CostPaise,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleCalls = `-- name: ListStaleCalls :many
SELECT id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason FROM calls
WHERE status IN ('dialing', 'ringing', 'in_progress')
  AND COALESCE(started_at, scheduled_for) < $1::timestamptz
ORDER BY scheduled_for
LIMIT 100
`

// Attempts stuck in a live state with no provider event for too long.
func (q *Queries) ListStaleCalls(ctx context.Context, cutoff time.Time) ([]Call, error) {
	rows, err := q.db.Query(ctx, listStaleCalls, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.ParentID,
			&i.AttemptNo,
			&i.ScheduledFor,
			&i.Status,
			&i.Provider,
			&i.ProviderCallID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.CostPaise,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCallDialing = `-- name: MarkCallDialing :execrows
UPDATE calls SET status = 'dialing' WHERE id = $1 AND status = 'scheduled'
`

// Committed before StartCall, so a re-run of place_call never dials twice.
func (q *Queries) MarkCallDialing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markCallDialing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFirstCallDone = `-- name: MarkFirstCallDone :exec
UPDATE parents SET first_call_done_at = $1 WHERE id = $2 AND first_call_done_at IS NULL
`

type MarkFirstCallDoneParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) MarkFirstCallDone(ctx context.Context, arg MarkFirstCallDoneParams) error {
	_, err := q.db.Exec(ctx, markFirstCallDone, arg.At, arg.ID)
	return err
}

const setCallUsage = `-- name: SetCallUsage :exec
UPDATE calls
SET duration_sec = COALESCE($1, duration_sec),
    cost_paise   = COALESCE($2, cost_paise)
WHERE id = $3
`

type SetCallUsageParams struct {
	DurationSec *int32
	CostPaise   *int64
	ID          uuid.UUID
}

// Duration and cost can arrive on a later event than the terminal one.
func (q *Queries) SetCallUsage(ctx context.Context, arg SetCallUsageParams) error {
	_, err := q.db.Exec(ctx, setCallUsage, arg.DurationSec, arg.CostPaise, arg.ID)
	return err
}

const setProviderCallID = `-- name: SetProviderCallID :execrows
UPDATE calls SET provider_call_id = $1
WHERE id = $2 AND provider_call_id IS NULL
`

type SetProviderCallIDParams struct {
	ProviderCallID *string
	ID             uuid.UUID
}

func (q *Queries) SetProviderCallID(ctx context.Context, arg SetProviderCallIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderCallID, arg.ProviderCallID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSlotStatus = `-- name: SetSlotStatus :execrows
UPDATE call_slots SET status = $1 WHERE id = $2 AND status = 'pending'
`

type SetSlotStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetSlotStatus(ctx context.Context, arg SetSlotStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSlotStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitionCall = `-- name: TransitionCall :execrows
UPDATE calls
SET status       = $1,
    started_at   = COALESCE(started_at, $2),
    ended_at     = COALESCE($3, ended_at),
    duration_sec = COALESCE($4, duration_sec),
    cost_paise   = COALESCE($5, cost_paise),
    end_reason   = COALESCE($6, end_reason)
WHERE id = $7 AND status = $8
`

type TransitionCallParams struct {
	ToStatus    string
	StartedAt   *time.Time
	EndedAt     *time.Time
	DurationSec *int32
	CostPaise   *int64
	EndReason   *string
	ID          uuid.UUID
	FromStatus  string
}

// Compare-and-set on the current status; optional fields keep their value
// when the argument is null.
func (q *Queries) TransitionCall(ctx context.Context, arg TransitionCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionCall,
		arg.ToStatus,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSec,
		arg.CostPaise,
		arg.EndReason,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
