// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: consents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listValidConsentKinds = `-- name: ListValidConsentKinds :many
SELECT DISTINCT kind FROM consents
WHERE parent_id = $1 AND withdrawn_at IS NULL
ORDER BY kind
`

func (q *Queries) ListValidConsentKinds(ctx context.Context, parentID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listValidConsentKinds, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordConsent = `-- name: RecordConsent :one
INSERT INTO consents (parent_id, kind, given_by, method, text_version, evidence_ref, given_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_id, kind, given_by, method, text_version, evidence_ref, given_at, withdrawn_at
`

type RecordConsentParams struct {
	ParentID    uuid.UUID
	Kind        string
	GivenBy     string
	Method      string
	TextVersion string
	EvidenceRef *string
	GivenAt     time.Time
}

func (q *Queries) RecordConsent(ctx context.Context, arg RecordConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, recordConsent,
		arg.ParentID,
		arg.Kind,
		arg.GivenBy,
		arg.Method,
		arg.TextVersion,
		arg.EvidenceRef,
		arg.GivenAt,
	)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.GivenBy,
		&i.Method,
		&i.TextVersion,
		&i.EvidenceRef,
		&i.GivenAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const withdrawConsent = `-- name: WithdrawConsent :execrows
UPDATE consents SET withdrawn_at = $3
WHERE parent_id = $1 AND kind = $2 AND withdrawn_at IS NULL
`

type WithdrawConsentParams struct {
	ParentID    uuid.UUID
	Kind        string
	WithdrawnAt *time.Time
}

func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawConsent, arg.ParentID, arg.Kind, arg.WithdrawnAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
