// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: context.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getParentWithAccount = `-- name: GetParentWithAccount :one
SELECT p.id, p.account_id, p.preferred_name, p.phone_e164, p.language, p.timezone, p.call_time_local, p.window_start, p.window_end, p.status, p.interests_enc, p.safe_word_enc, p.local_contact_name, p.local_contact_phone_e164, p.first_call_done_at, p.created_at, a.plan, a.status AS account_status
FROM parents p JOIN accounts a ON a.id = p.account_id
WHERE p.id = $1
`

type GetParentWithAccountRow struct {
	ID                    uuid.UUID
	AccountID             uuid.UUID
	PreferredName         string
	PhoneE164             string
	Language              string
	Timezone              string
	CallTimeLocal         pgtype.Time
	WindowStart           pgtype.Time
	WindowEnd             pgtype.Time
	Status                string
	InterestsEnc          []byte
	SafeWordEnc           []byte
	LocalContactName      *string
	LocalContactPhoneE164 *string
	FirstCallDoneAt       *time.Time
	CreatedAt             time.Time
	Plan                  string
	AccountStatus         string
}

func (q *Queries) GetParentWithAccount(ctx context.Context, id uuid.UUID) (GetParentWithAccountRow, error) {
	row := q.db.QueryRow(ctx, getParentWithAccount, id)
	var i GetParentWithAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreferredName,
		&i.PhoneE164,
		&i.Language,
		&i.Timezone,
		&i.CallTimeLocal,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Status,
		&i.InterestsEnc,
		&i.SafeWordEnc,
		&i.LocalContactName,
		&i.LocalContactPhoneE164,
		&i.FirstCallDoneAt,
		&i.CreatedAt,
		&i.Plan,
		&i.AccountStatus,
	)
	return i, err
}

const insertMemory = `-- name: InsertMemory :one
INSERT INTO memories (parent_id, kind, content_enc, source_call_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertMemoryParams struct {
	ParentID     uuid.UUID
	Kind         string
	ContentEnc   []byte
	SourceCallID *uuid.UUID
	ExpiresAt    *time.Time
}

func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMemory,
		arg.ParentID,
		arg.Kind,
		arg.ContentEnc,
		arg.SourceCallID,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listActiveFollowUps = `-- name: ListActiveFollowUps :many
SELECT id, parent_id, kind, content_enc, source_call_id, expires_at, created_at FROM memories
WHERE parent_id = $1 AND kind = 'follow_up'
  AND (expires_at IS NULL OR expires_at > $2)
ORDER BY created_at DESC, id
LIMIT $3
`

type ListActiveFollowUpsParams struct {
	ParentID uuid.UUID
	Now      *time.Time
	MaxItems int32
}

func (q *Queries) ListActiveFollowUps(ctx context.Context, arg ListActiveFollowUpsParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listActiveFollowUps, arg.ParentID, arg.Now, arg.MaxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.ContentEnc,
			&i.SourceCallID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
