// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package db

import (
	"context"
	"time"
)

const cancelQueuedJobsForParent = `-- name: CancelQueuedJobsForParent :execrows
UPDATE jobs
SET status = 'failed', last_error = 'cancelled: ' || $1::text
WHERE status = 'queued' AND payload->>'parent_id' = $2::text
`

type CancelQueuedJobsForParentParams struct {
	Reason   string
	ParentID string
}

// Used when consent is withdrawn or a stop is requested.
func (q *Queries) CancelQueuedJobsForParent(ctx context.Context, arg CancelQueuedJobsForParentParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelQueuedJobsForParent, arg.Reason, arg.ParentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', locked_by = $1::text, locked_at = $2::timestamptz, attempts = attempts + 1
WHERE id = (
  SELECT j.id FROM jobs j
  WHERE j.status = 'queued' AND j.run_at <= $2::timestamptz AND j.kind = ANY($3::text[])
  ORDER BY j.run_at, j.id
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, kind, dedupe_key, payload, run_at, status, attempts, max_attempts, locked_by, locked_at, last_error
`

type ClaimJobParams struct {
	WorkerID string
	Now      time.Time
	Kinds    []string
}

// SPEC §5 claim, limited to the kinds this worker handles. now comes from the
// injectable clock rather than SQL now().
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.WorkerID, arg.Now, arg.Kinds)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DedupeKey,
		&i.Payload,
		&i.RunAt,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET status = 'done', locked_by = NULL, locked_at = NULL, last_error = NULL
WHERE id = $1 AND status = 'running' AND locked_by = $2::text AND attempts = $3
`

type CompleteJobParams struct {
	ID       int64
	WorkerID string
	Attempts int32
}

// locked_by and attempts fence out a worker whose lock was reaped.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.WorkerID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT kind, status, count(*)::bigint AS n FROM jobs GROUP BY kind, status ORDER BY kind, status
`

type CountJobsByStatusRow struct {
	Kind   string
	Status string
	N      int64
}

func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountJobsByStatusRow
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Kind, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFinishedJobsBefore = `-- name: DeleteFinishedJobsBefore :execrows
DELETE FROM jobs WHERE status IN ('done', 'failed') AND run_at < $1
`

// Retention for the queue itself; done and failed rows hold IDs only.
func (q *Queries) DeleteFinishedJobsBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedJobsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (kind, dedupe_key, payload, run_at, max_attempts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (dedupe_key) DO NOTHING
RETURNING id
`

type EnqueueJobParams struct {
	Kind        string
	DedupeKey   *string
	Payload     []byte
	RunAt       time.Time
	MaxAttempts int32
}

// A duplicate dedupe_key inserts nothing and returns no row.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Kind,
		arg.DedupeKey,
		arg.Payload,
		arg.RunAt,
		arg.MaxAttempts,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failJob = `-- name: FailJob :execrows
UPDATE jobs
SET status = 'failed', locked_by = NULL, locked_at = NULL, last_error = $1
WHERE id = $2 AND status = 'running' AND locked_by = $3::text AND attempts = $4
`

type FailJobParams struct {
	LastError *string
	ID        int64
	WorkerID  string
	Attempts  int32
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, dedupe_key, payload, run_at, status, attempts, max_attempts, locked_by, locked_at, last_error FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DedupeKey,
		&i.Payload,
		&i.RunAt,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
	)
	return i, err
}

const reapStaleJobs = `-- name: ReapStaleJobs :many
UPDATE jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'queued' END,
    locked_by = NULL, locked_at = NULL, last_error = 'lock expired'
WHERE status = 'running' AND locked_at < $1::timestamptz
RETURNING id, kind, dedupe_key, payload, run_at, status, attempts, max_attempts, locked_by, locked_at, last_error
`

// Requeue running jobs whose lock expired. A job that has used every attempt
// fails instead, so a job that crashes its worker cannot loop forever.
func (q *Queries) ReapStaleJobs(ctx context.Context, cutoff time.Time) ([]Job, error) {
	rows, err := q.db.Query(ctx, reapStaleJobs, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DedupeKey,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET status = 'queued', locked_by = NULL, locked_at = NULL, run_at = $1, last_error = $2
WHERE id = $3 AND status = 'running' AND locked_by = $4::text AND attempts = $5
`

type RetryJobParams struct {
	RunAt     time.Time
	LastError *string
	ID        int64
	WorkerID  string
	Attempts  int32
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.RunAt,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
