// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maintenance.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredTranscripts = `-- name: DeleteExpiredTranscripts :execrows
DELETE FROM transcripts WHERE delete_after <= $1
`

func (q *Queries) DeleteExpiredTranscripts(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTranscripts, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldAudit = `-- name: DeleteOldAudit :execrows
DELETE FROM audit_log WHERE at < $1
`

func (q *Queries) DeleteOldAudit(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAudit, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldInbound = `-- name: DeleteOldInbound :execrows
DELETE FROM inbound_messages WHERE received_at < $1
`

func (q *Queries) DeleteOldInbound(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldInbound, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldWebhookEvents = `-- name: DeleteOldWebhookEvents :execrows
DELETE FROM webhook_events WHERE received_at < $1
`

func (q *Queries) DeleteOldWebhookEvents(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldWebhookEvents, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpiredTranscriptCalls = `-- name: ListExpiredTranscriptCalls :many
SELECT c.id, c.provider, c.provider_call_id FROM transcripts t JOIN calls c ON c.id = t.call_id
WHERE t.delete_after <= $1
`

type ListExpiredTranscriptCallsRow struct {
	ID             uuid.UUID
	Provider       string
	ProviderCallID *string
}

// Calls whose transcripts are due for deletion, so recordings at the voice
// platform can be deleted too.
func (q *Queries) ListExpiredTranscriptCalls(ctx context.Context, now time.Time) ([]ListExpiredTranscriptCallsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredTranscriptCalls, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredTranscriptCallsRow
	for rows.Next() {
		var i ListExpiredTranscriptCallsRow
		if err := rows.Scan(&i.ID, &i.Provider, &i.ProviderCallID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
