// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          uuid.UUID
	Plan        string
	Status      string
	BillingNote *string
	CreatedAt   time.Time
}

type Alert struct {
	ID             uuid.UUID
	ParentID       uuid.UUID
	CallID         *uuid.UUID
	SlotID         *uuid.UUID
	Type           string
	Category       string
	Source         string
	DetailEnc      []byte
	Status         string
	EscalationStep int32
	AcknowledgedBy *uuid.UUID
	AcknowledgedAt *time.Time
	ReviewedBy     *string
	ReviewedAt     *time.Time
	ReviewNoteEnc  []byte
	CreatedAt      time.Time
}

type AuditLog struct {
	ID       int64
	Actor    string
	Action   string
	Entity   string
	EntityID string
	At       time.Time
	Details  []byte
}

type Call struct {
	ID             uuid.UUID
	SlotID         uuid.UUID
	ParentID       uuid.UUID
	AttemptNo      int32
	ScheduledFor   time.Time
	Status         string
	Provider       string
	ProviderCallID *string
	StartedAt      *time.Time
	EndedAt        *time.Time
	DurationSec    *int32
	CostPaise      *int64
	EndReason      *string
}

type CallReport struct {
	CallID        uuid.UUID
	SchemaVersion string
	ReportEnc     []byte
	RedFlagCount  int32
	Confidence    float32
	NeedsReview   bool
	Model         string
	CreatedAt     time.Time
}

type CallSlot struct {
	ID        uuid.UUID
	ParentID  uuid.UUID
	LocalDate pgtype.Date
	Status    string
}

type Consent struct {
	ID          uuid.UUID
	ParentID    uuid.UUID
	Kind        string
	GivenBy     string
	Method      string
	TextVersion string
	EvidenceRef *string
	GivenAt     time.Time
	WithdrawnAt *time.Time
}

type FamilyMember struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Name            string
	PhoneE164       string
	Relation        *string
	Language        string
	Priority        int32
	WhatsappOptInAt *time.Time
	CreatedAt       time.Time
}

type InboundMessage struct {
	ID             uuid.UUID
	FamilyMemberID *uuid.UUID
	FromE164       string
	Kind           string
	BodyEnc        []byte
	HandledAt      *time.Time
	ReceivedAt     time.Time
}

type Job struct {
	ID          int64
	Kind        string
	DedupeKey   *string
	Payload     []byte
	RunAt       time.Time
	Status      string
	Attempts    int32
	MaxAttempts int32
	LockedBy    *string
	LockedAt    *time.Time
	LastError   *string
	Priority    int16
}

type Medicine struct {
	ID       uuid.UUID
	ParentID uuid.UUID
	NameEnc  []byte
	Timing   string
	Active   bool
}

type Memory struct {
	ID           uuid.UUID
	ParentID     uuid.UUID
	Kind         string
	ContentEnc   []byte
	SourceCallID *uuid.UUID
	ExpiresAt    *time.Time
	CreatedAt    time.Time
}

type Notification struct {
	ID                uuid.UUID
	AlertID           *uuid.UUID
	CallID            *uuid.UUID
	FamilyMemberID    *uuid.UUID
	RecipientKind     string
	Channel           string
	Template          string
	ProviderMessageID *string
	Status            string
	Error             *string
	CreatedAt         time.Time
	DedupeKey         *string
	SentAt            *time.Time
}

type Parent struct {
	ID                    uuid.UUID
	AccountID             uuid.UUID
	PreferredName         string
	PhoneE164             string
	Language              string
	Timezone              string
	CallTimeLocal         pgtype.Time
	WindowStart           pgtype.Time
	WindowEnd             pgtype.Time
	Status                string
	InterestsEnc          []byte
	SafeWordEnc           []byte
	LocalContactName      *string
	LocalContactPhoneE164 *string
	FirstCallDoneAt       *time.Time
	CreatedAt             time.Time
}

type Transcript struct {
	CallID      uuid.UUID
	TurnsEnc    []byte
	Language    *string
	DeleteAfter time.Time
}

type WebhookEvent struct {
	Provider   string
	EventID    string
	ReceivedAt time.Time
}
