// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts a SET status = 'acknowledged', acknowledged_by = $1, acknowledged_at = $2
FROM parents p, family_members m
WHERE a.id = $3 AND p.id = a.parent_id AND m.id = $1 AND m.account_id = p.account_id
  AND a.status IN ('open', 'notified')
RETURNING a.id, a.parent_id
`

type AcknowledgeAlertParams struct {
	MemberID *uuid.UUID
	At       *time.Time
	AlertID  uuid.UUID
}

type AcknowledgeAlertRow struct {
	ID       uuid.UUID
	ParentID uuid.UUID
}

// Only someone in the alert's family can acknowledge it.
func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (AcknowledgeAlertRow, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.MemberID, arg.At, arg.AlertID)
	var i AcknowledgeAlertRow
	err := row.Scan(&i.ID, &i.ParentID)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, account_id, name, phone_e164, relation, language, priority, whatsapp_opt_in_at, created_at FROM family_members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id uuid.UUID) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i FamilyMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.PhoneE164,
		&i.Relation,
		&i.Language,
		&i.Priority,
		&i.WhatsappOptInAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInboundMessage = `-- name: InsertInboundMessage :one
INSERT INTO inbound_messages (family_member_id, from_e164, kind, body_enc, handled_at, received_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertInboundMessageParams struct {
	FamilyMemberID *uuid.UUID
	FromE164       string
	Kind           string
	BodyEnc        []byte
	HandledAt      *time.Time
	ReceivedAt     time.Time
}

func (q *Queries) InsertInboundMessage(ctx context.Context, arg InsertInboundMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertInboundMessage,
		arg.FamilyMemberID,
		arg.FromE164,
		arg.Kind,
		arg.BodyEnc,
		arg.HandledAt,
		arg.ReceivedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listMembersByPhone = `-- name: ListMembersByPhone :many
SELECT id, account_id, name, phone_e164, relation, language, priority, whatsapp_opt_in_at, created_at FROM family_members WHERE phone_e164 = $1 ORDER BY created_at
`

func (q *Queries) ListMembersByPhone(ctx context.Context, phoneE164 string) ([]FamilyMember, error) {
	rows, err := q.db.Query(ctx, listMembersByPhone, phoneE164)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamilyMember
	for rows.Next() {
		var i FamilyMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.PhoneE164,
			&i.Relation,
			&i.Language,
			&i.Priority,
			&i.WhatsappOptInAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForParent = `-- name: ListNotificationsForParent :many
SELECT n.id, n.alert_id, n.call_id, n.family_member_id, n.recipient_kind, n.channel, n.template, n.provider_message_id, n.status, n.error, n.created_at, n.dedupe_key, n.sent_at FROM notifications n
LEFT JOIN alerts a ON a.id = n.alert_id
LEFT JOIN calls c ON c.id = n.call_id
WHERE a.parent_id = $1 OR c.parent_id = $1
ORDER BY n.created_at, n.id
`

func (q *Queries) ListNotificationsForParent(ctx context.Context, parentID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.CallID,
			&i.FamilyMemberID,
			&i.RecipientKind,
			&i.Channel,
			&i.Template,
			&i.ProviderMessageID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.DedupeKey,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchAlertsForCall = `-- name: ListWatchAlertsForCall :many
SELECT id, parent_id, call_id, slot_id, type, category, source, detail_enc, status, escalation_step, acknowledged_by, acknowledged_at, reviewed_by, reviewed_at, review_note_enc, created_at FROM alerts WHERE call_id = $1 AND type = 'watch' ORDER BY created_at, id
`

func (q *Queries) ListWatchAlertsForCall(ctx context.Context, callID *uuid.UUID) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listWatchAlertsForCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CallID,
			&i.SlotID,
			&i.Type,
			&i.Category,
			&i.Source,
			&i.DetailEnc,
			&i.Status,
			&i.EscalationStep,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNoteEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertNotified = `-- name: MarkAlertNotified :exec
UPDATE alerts
SET status = CASE WHEN status = 'open' THEN 'notified' ELSE status END,
    escalation_step = GREATEST(escalation_step, $1)
WHERE id = $2
`

type MarkAlertNotifiedParams struct {
	Step int32
	ID   uuid.UUID
}

func (q *Queries) MarkAlertNotified(ctx context.Context, arg MarkAlertNotifiedParams) error {
	_, err := q.db.Exec(ctx, markAlertNotified, arg.Step, arg.ID)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications SET status = 'failed', error = $1 WHERE id = $2 AND status IN ('queued', 'failed')
`

type MarkNotificationFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.Error, arg.ID)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications SET status = 'sent', provider_message_id = $1, error = NULL, sent_at = $2
WHERE id = $3
`

type MarkNotificationSentParams struct {
	ProviderMessageID *string
	SentAt            *time.Time
	ID                uuid.UUID
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.ProviderMessageID, arg.SentAt, arg.ID)
	return err
}

const updateNotificationDelivery = `-- name: UpdateNotificationDelivery :execrows
UPDATE notifications SET status = $1
WHERE provider_message_id = $2
  AND (
    ($1 = 'delivered' AND status IN ('queued', 'sent'))
    OR ($1 = 'read' AND status IN ('queued', 'sent', 'delivered'))
    OR ($1 = 'failed' AND status IN ('queued', 'sent'))
  )
`

type UpdateNotificationDeliveryParams struct {
	Status            string
	ProviderMessageID *string
}

// Delivery statuses only move forward; failed can arrive at any point.
func (q *Queries) UpdateNotificationDelivery(ctx context.Context, arg UpdateNotificationDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationDelivery, arg.Status, arg.ProviderMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertNotification = `-- name: UpsertNotification :one
INSERT INTO notifications (alert_id, call_id, family_member_id, recipient_kind, channel, template, dedupe_key, created_at)
VALUES ($1, $2, $3, $4, 'whatsapp', $5, $6, $7)
ON CONFLICT (dedupe_key) WHERE dedupe_key IS NOT NULL DO UPDATE SET dedupe_key = EXCLUDED.dedupe_key
RETURNING id, alert_id, call_id, family_member_id, recipient_kind, channel, template, provider_message_id, status, error, created_at, dedupe_key, sent_at
`

type UpsertNotificationParams struct {
	AlertID        *uuid.UUID
	CallID         *uuid.UUID
	FamilyMemberID *uuid.UUID
	RecipientKind  string
	Template       string
	DedupeKey      *string
	CreatedAt      time.Time
}

// Creates the row for a logical send, or returns the existing one.
func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, upsertNotification,
		arg.AlertID,
		arg.CallID,
		arg.FamilyMemberID,
		arg.RecipientKind,
		arg.Template,
		arg.DedupeKey,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.CallID,
		&i.FamilyMemberID,
		&i.RecipientKind,
		&i.Channel,
		&i.Template,
		&i.ProviderMessageID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.DedupeKey,
		&i.SentAt,
	)
	return i, err
}
