// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: parents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMedicine = `-- name: CreateMedicine :one
INSERT INTO medicines (parent_id, name_enc, timing)
VALUES ($1, $2, $3)
RETURNING id, parent_id, name_enc, timing, active
`

type CreateMedicineParams struct {
	ParentID uuid.UUID
	NameEnc  []byte
	Timing   string
}

func (q *Queries) CreateMedicine(ctx context.Context, arg CreateMedicineParams) (Medicine, error) {
	row := q.db.QueryRow(ctx, createMedicine, arg.ParentID, arg.NameEnc, arg.Timing)
	var i Medicine
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.NameEnc,
		&i.Timing,
		&i.Active,
	)
	return i, err
}

const createParent = `-- name: CreateParent :one
INSERT INTO parents (
  account_id, preferred_name, phone_e164, language, timezone, call_time_local,
  window_start, window_end, interests_enc, safe_word_enc,
  local_contact_name, local_contact_phone_e164
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, account_id, preferred_name, phone_e164, language, timezone, call_time_local, window_start, window_end, status, interests_enc, safe_word_enc, local_contact_name, local_contact_phone_e164, first_call_done_at, created_at
`

type CreateParentParams struct {
	AccountID             uuid.UUID
	PreferredName         string
	PhoneE164             string
	Language              string
	Timezone              string
	CallTimeLocal         pgtype.Time
	WindowStart           pgtype.Time
	WindowEnd             pgtype.Time
	InterestsEnc          []byte
	SafeWordEnc           []byte
	LocalContactName      *string
	LocalContactPhoneE164 *string
}

func (q *Queries) CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, createParent,
		arg.AccountID,
		arg.PreferredName,
		arg.PhoneE164,
		arg.Language,
		arg.Timezone,
		arg.CallTimeLocal,
		arg.WindowStart,
		arg.WindowEnd,
		arg.InterestsEnc,
		arg.SafeWordEnc,
		arg.LocalContactName,
		arg.LocalContactPhoneE164,
	)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreferredName,
		&i.PhoneE164,
		&i.Language,
		&i.Timezone,
		&i.CallTimeLocal,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Status,
		&i.InterestsEnc,
		&i.SafeWordEnc,
		&i.LocalContactName,
		&i.LocalContactPhoneE164,
		&i.FirstCallDoneAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParent = `-- name: GetParent :one
SELECT id, account_id, preferred_name, phone_e164, language, timezone, call_time_local, window_start, window_end, status, interests_enc, safe_word_enc, local_contact_name, local_contact_phone_e164, first_call_done_at, created_at FROM parents WHERE id = $1
`

func (q *Queries) GetParent(ctx context.Context, id uuid.UUID) (Parent, error) {
	row := q.db.QueryRow(ctx, getParent, id)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreferredName,
		&i.PhoneE164,
		&i.Language,
		&i.Timezone,
		&i.CallTimeLocal,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Status,
		&i.InterestsEnc,
		&i.SafeWordEnc,
		&i.LocalContactName,
		&i.LocalContactPhoneE164,
		&i.FirstCallDoneAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveMedicines = `-- name: ListActiveMedicines :many
SELECT id, parent_id, name_enc, timing, active FROM medicines WHERE parent_id = $1 AND active ORDER BY timing, id
`

func (q *Queries) ListActiveMedicines(ctx context.Context, parentID uuid.UUID) ([]Medicine, error) {
	rows, err := q.db.Query(ctx, listActiveMedicines, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medicine
	for rows.Next() {
		var i Medicine
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.NameEnc,
			&i.Timing,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setParentStatus = `-- name: SetParentStatus :exec
UPDATE parents SET status = $2 WHERE id = $1
`

type SetParentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetParentStatus(ctx context.Context, arg SetParentStatusParams) error {
	_, err := q.db.Exec(ctx, setParentStatus, arg.ID, arg.Status)
	return err
}
