// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const callReportExists = `-- name: CallReportExists :one
SELECT EXISTS (SELECT 1 FROM call_reports WHERE call_id = $1)
`

func (q *Queries) CallReportExists(ctx context.Context, callID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, callReportExists, callID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteTranscript = `-- name: DeleteTranscript :execrows
DELETE FROM transcripts WHERE call_id = $1
`

func (q *Queries) DeleteTranscript(ctx context.Context, callID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTranscript, callID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCallReport = `-- name: GetCallReport :one
SELECT call_id, schema_version, report_enc, red_flag_count, confidence, needs_review, model, created_at FROM call_reports WHERE call_id = $1
`

func (q *Queries) GetCallReport(ctx context.Context, callID uuid.UUID) (CallReport, error) {
	row := q.db.QueryRow(ctx, getCallReport, callID)
	var i CallReport
	err := row.Scan(
		&i.CallID,
		&i.SchemaVersion,
		&i.ReportEnc,
		&i.RedFlagCount,
		&i.Confidence,
		&i.NeedsReview,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const insertCallReport = `-- name: InsertCallReport :execrows
INSERT INTO call_reports (call_id, schema_version, report_enc, red_flag_count, confidence, needs_review, model, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (call_id) DO NOTHING
`

type InsertCallReportParams struct {
	CallID        uuid.UUID
	SchemaVersion string
	ReportEnc     []byte
	RedFlagCount  int32
	Confidence    float32
	NeedsReview   bool
	Model         string
	CreatedAt     time.Time
}

func (q *Queries) InsertCallReport(ctx context.Context, arg InsertCallReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCallReport,
		arg.CallID,
		arg.SchemaVersion,
		arg.ReportEnc,
		arg.RedFlagCount,
		arg.Confidence,
		arg.NeedsReview,
		arg.Model,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOptedInMembers = `-- name: ListOptedInMembers :many
SELECT id, account_id, name, phone_e164, relation, language, priority, whatsapp_opt_in_at, created_at FROM family_members
WHERE account_id = $1 AND whatsapp_opt_in_at IS NOT NULL
ORDER BY priority
`

func (q *Queries) ListOptedInMembers(ctx context.Context, accountID uuid.UUID) ([]FamilyMember, error) {
	rows, err := q.db.Query(ctx, listOptedInMembers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamilyMember
	for rows.Next() {
		var i FamilyMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.PhoneE164,
			&i.Relation,
			&i.Language,
			&i.Priority,
			&i.WhatsappOptInAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReports = `-- name: ListRecentReports :many
SELECT r.call_id, r.schema_version, r.report_enc, r.red_flag_count, r.confidence, r.needs_review, r.model, r.created_at FROM call_reports r
JOIN calls c ON c.id = r.call_id
WHERE c.parent_id = $1 AND r.call_id <> $2 AND r.schema_version = '1'
  AND r.created_at <= $3
ORDER BY r.created_at DESC
LIMIT $4
`

type ListRecentReportsParams struct {
	ParentID      uuid.UUID
	ExcludeCallID uuid.UUID
	Before        time.Time
	MaxItems      int32
}

// Earlier valid reports for a parent, newest first, for multi-call rules.
func (q *Queries) ListRecentReports(ctx context.Context, arg ListRecentReportsParams) ([]CallReport, error) {
	rows, err := q.db.Query(ctx, listRecentReports,
		arg.ParentID,
		arg.ExcludeCallID,
		arg.Before,
		arg.MaxItems,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallReport
	for rows.Next() {
		var i CallReport
		if err := rows.Scan(
			&i.CallID,
			&i.SchemaVersion,
			&i.ReportEnc,
			&i.RedFlagCount,
			&i.Confidence,
			&i.NeedsReview,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
