// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheduler.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCallGuardState = `-- name: GetCallGuardState :one
SELECT c.id AS call_id, c.status AS call_status, c.attempt_no, c.slot_id,
       p.id AS parent_id, p.status AS parent_status, p.phone_e164, p.timezone,
       p.call_time_local, p.window_start, p.window_end,
       a.status AS account_status, a.plan,
       ARRAY(
         SELECT DISTINCT cs.kind FROM consents cs
         WHERE cs.parent_id = p.id AND cs.withdrawn_at IS NULL AND cs.given_at <= $1
         ORDER BY cs.kind
       )::text[] AS consent_kinds
FROM calls c
JOIN parents p ON p.id = c.parent_id
JOIN accounts a ON a.id = p.account_id
WHERE c.id = $2
`

type GetCallGuardStateParams struct {
	Now    time.Time
	CallID uuid.UUID
}

type GetCallGuardStateRow struct {
	CallID        uuid.UUID
	CallStatus    string
	AttemptNo     int32
	SlotID        uuid.UUID
	ParentID      uuid.UUID
	ParentStatus  string
	PhoneE164     string
	Timezone      string
	CallTimeLocal pgtype.Time
	WindowStart   pgtype.Time
	WindowEnd     pgtype.Time
	AccountStatus string
	Plan          string
	ConsentKinds  []string
}

// Everything place_call needs to re-check its guards in one read.
func (q *Queries) GetCallGuardState(ctx context.Context, arg GetCallGuardStateParams) (GetCallGuardStateRow, error) {
	row := q.db.QueryRow(ctx, getCallGuardState, arg.Now, arg.CallID)
	var i GetCallGuardStateRow
	err := row.Scan(
		&i.CallID,
		&i.CallStatus,
		&i.AttemptNo,
		&i.SlotID,
		&i.ParentID,
		&i.ParentStatus,
		&i.PhoneE164,
		&i.Timezone,
		&i.CallTimeLocal,
		&i.WindowStart,
		&i.WindowEnd,
		&i.AccountStatus,
		&i.Plan,
		&i.ConsentKinds,
	)
	return i, err
}

const insertCallAttempt = `-- name: InsertCallAttempt :one
INSERT INTO calls (slot_id, parent_id, attempt_no, scheduled_for, provider)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slot_id, parent_id, attempt_no, scheduled_for, status, provider, provider_call_id, started_at, ended_at, duration_sec, cost_paise, end_reason
`

type InsertCallAttemptParams struct {
	SlotID       uuid.UUID
	ParentID     uuid.UUID
	AttemptNo    int32
	ScheduledFor time.Time
	Provider     string
}

func (q *Queries) InsertCallAttempt(ctx context.Context, arg InsertCallAttemptParams) (Call, error) {
	row := q.db.QueryRow(ctx, insertCallAttempt,
		arg.SlotID,
		arg.ParentID,
		arg.AttemptNo,
		arg.ScheduledFor,
		arg.Provider,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.ParentID,
		&i.AttemptNo,
		&i.ScheduledFor,
		&i.Status,
		&i.Provider,
		&i.ProviderCallID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.CostPaise,
		&i.EndReason,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :one
INSERT INTO call_slots (parent_id, local_date)
VALUES ($1, $2)
ON CONFLICT (parent_id, local_date) DO NOTHING
RETURNING id
`

type InsertSlotParams struct {
	ParentID  uuid.UUID
	LocalDate pgtype.Date
}

// Returns no row when today's slot already exists.
func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSlot, arg.ParentID, arg.LocalDate)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listSchedulableParents = `-- name: ListSchedulableParents :many
SELECT p.id, p.phone_e164, p.timezone, p.call_time_local, p.window_start, p.window_end, a.plan
FROM parents p
JOIN accounts a ON a.id = p.account_id
WHERE p.status = 'active'
  AND a.status IN ('trial', 'active')
  AND (
    SELECT count(DISTINCT c.kind) FROM consents c
    WHERE c.parent_id = p.id
      AND c.withdrawn_at IS NULL
      AND c.given_at <= $1
      AND c.kind IN ('calls', 'data_processing', 'share_with_family')
  ) = 3
ORDER BY p.id
`

type ListSchedulableParentsRow struct {
	ID            uuid.UUID
	PhoneE164     string
	Timezone      string
	CallTimeLocal pgtype.Time
	WindowStart   pgtype.Time
	WindowEnd     pgtype.Time
	Plan          string
}

// Parents the scheduler may create slots for: active parent, callable account,
// and the three consents required before any call (SPEC §13), none withdrawn.
func (q *Queries) ListSchedulableParents(ctx context.Context, now time.Time) ([]ListSchedulableParentsRow, error) {
	rows, err := q.db.Query(ctx, listSchedulableParents, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulableParentsRow
	for rows.Next() {
		var i ListSchedulableParentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhoneE164,
			&i.Timezone,
			&i.CallTimeLocal,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slotExists = `-- name: SlotExists :one
SELECT EXISTS (SELECT 1 FROM call_slots WHERE parent_id = $1 AND local_date = $2)
`

type SlotExistsParams struct {
	ParentID  uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) SlotExists(ctx context.Context, arg SlotExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, slotExists, arg.ParentID, arg.LocalDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
